### PR TITLE
Add us-core-5 data to initdb.sql

### PR DESCRIPTION
**Pull request by yunwwang**
# Summary
This Pull Request updates FHIR data to be compatible with US Core v5.0.1

To update your server, 
1. stop docker
2. follow the READ.me to remove the old database
3. run `bundle install`
4. restart docker

Also attach the Bundle transaction file for all the changes

## Code changes
* initdb.sql

## Testing guidance
1. update inferno server as mentioned above
2. run (g)(10) test kit with US Core 5.0.1. 
3. Tests shall pass without data error
[us-core-501-update.json.zip](https://github.com/inferno-framework/inferno-reference-server/files/10058106/us-core-501-update.json.zip)

### CODE REVIEW

**Comment by arscan** [comment]
We added a 'Media' resource type, linked from diagnosticreport?  We'll have to make sure our g10 presets have that in the scope, because I'm getting an access denied right now when going through g10.  I imagine this doesn't happen when just using the us core suite directly though.

**Comment by arscan** [comment]
I've come across the following errors when running g10 single patient api tests in us core against it (so, perhaps you've addressed these in US Core but haven't yet gotten them into g10).  Are all of these issues with the tests themselves?

SDOH: Resource does not conform to the profile http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-sdoh-assessment|5.0.1

Social History: Resource does not conform to the profile http://hl7.org/fhir/us/core/StructureDefinition/us-core-observation-social-history|5.0.1

Provenance: Resource does not conform to the profile http://hl7.org/fhir/us/core/StructureDefinition/us-core-provenance|5.0.1

**Comment by yunwwang** [comment]
The SDOH and Social History errors are addressed by this PR in US Core repo: https://github.com/inferno-framework/us-core-test-kit/pull/93

The Provenance error is caused by IG constraints. See https://chat.fhir.org/#narrow/stream/179190-united-states/topic/Validation.20error.20on.20Provenance. We need to figure out how do address this one while waiting for US Core's resolution

**Review by arscan — APPROVED** [review]
Looks good.  Don't forget to update the from-scratch transaction in the uscore-data-sets repo too.  Afterwards we probably should reevaluate how all these tie together, but in the meantime we probably should just update that so we are consistent.

**Pull request merged**
